name: Build Android APK

on:
  workflow_dispatch: # Allows you to run this manually whenever you want
  push:
    branches: [ "main", "master" ]

jobs:
  build-android:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Database Directory
        run: mkdir -p database

      - name: Download Database from Google Drive
        # This grabs your DB file on the fly and places it right where Buildozer expects it
        run: |
          wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=13cJresq-tUmD6dFH7xK9YV04c49_acCy' -O database/offlinedata.db

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade buildozer cython virtualenv

      - name: Build APK with Buildozer
        # This will automatically accept Android SDK licenses and build the APK
        run: |
          yes | buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: bin/*.apk
